version: 1
environments:
  D0001-EMT:
    web:
      farm:
        app:
          sku_name: B1
          worker_count: 1
          os_type: Windows

      app:
        web:
          deploy_type: code
          https_only: true
          always_on: true
          ftps_state: Disabled
          minimum_tls_version: "1.2"
          app_settings:
            ASPNETCORE_ENVIRONMENT: Development
    network:
      nsg:
        apim-internal:
          security_rules:
            sr-in-allow-mgt-apim:
              priority: 100
              direction: Inbound
              access: Allow
              protocol: Tcp
              source_port_range: "*"
              destination_port_range: "3443"
              source_address_prefix: ApiManagement
              destination_address_prefix: VirtualNetwork
            sr-in-allow-load-balancer:
              priority: 101
              direction: Inbound
              access: Allow
              protocol: Tcp
              source_port_range: "*"
              destination_port_range: "6390"
              source_address_prefix: AzureLoadBalancer
              destination_address_prefix: VirtualNetwork
            sr-out-allow-load-balancer:
              priority: 100
              direction: Outbound
              access: Allow
              protocol: Tcp
              source_port_range: "*"
              destination_port_range: "80"
              source_address_prefix: VirtualNetwork
              destination_address_prefix: Internet
      vnet:
        address_space:
          - 10.10.0.0/16
        subnets:
          sn-web-integration:
            address_prefixes:
              - 10.10.1.0/24
          sn-private-endpoint:
            address_prefixes:
              - 10.10.2.0/24
          sn-apimv1-internal-injection:
            address_prefixes:
              - 10.10.3.0/24
            nsg_key: apim-internal
    apim:
      publisher_name: Platform Team
      publisher_email: platform@example.com
      sku_name: Developer_1
      virtual_network_type: Internal
      subnet_key: sn-apimv1-internal-injection

  T0001-EMT:
    web:
      farm:
        app:
          sku_name: B1
          worker_count: 1
          os_type: Windows

      app:
        web:
          deploy_type: code
          https_only: true
          always_on: true
          ftps_state: Disabled
          minimum_tls_version: "1.2"
          app_settings:
            ASPNETCORE_ENVIRONMENT: Test
